pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "AllToolbox"
include ":app"
include ":core"
include ":file-browser"
include ":file-ops"
include ":archive"
include ":cleanup"
include ":editor"
include ":apk-tools"
include ":security"
include ":root"
include ":transfer"