// hide 模块 —— 文件隐身/伪装（隐藏文件、伪装为其它类型）
plugins {
    id 'com.android.library'
}

android {
    namespace 'com.alltoolbox.hide'
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':core')

    implementation "androidx.appcompat:appcompat:${rootProject.ext.appcompatVersion}"
    implementation "com.google.android.material:material:${rootProject.ext.materialVersion}"
    implementation "androidx.recyclerview:recyclerview:${rootProject.ext.recyclerviewVersion}"
}